var codestr="";
codestr=codestr+"<head>\n";
codestr=codestr+"<title>发送信息</title>\n";
codestr=codestr+"<meta http-equiv=\"Content-Type\" content=\"text/html;charset=\"gb2312\">\n";
codestr=codestr+"<style type=\"text/css\">\n";
codestr=codestr+"<!--\n";
codestr=codestr+"body {  font-family: \"宋体\"; font-size: 9pt;}\n";
codestr=codestr+"td {font-family:\"宋体\";font-size:9pt;}\n";
codestr=codestr+"A:link\n";
codestr=codestr+"{\n";
codestr=codestr+"    COLOR: black;\n";
codestr=codestr+"    TEXT-DECORATION: none\n";
codestr=codestr+"}\n";
codestr=codestr+"A:active\n";
codestr=codestr+"{\n";
codestr=codestr+"    COLOR: black;\n";
codestr=codestr+"    TEXT-DECORATION: none\n";
codestr=codestr+"}\n";
codestr=codestr+"A:visited\n";
codestr=codestr+"{\n";
codestr=codestr+"    COLOR: black;\n";
codestr=codestr+"    TEXT-DECORATION: none\n";
codestr=codestr+"}\n";
codestr=codestr+"A\n";
codestr=codestr+"{\n";
codestr=codestr+"COLOR: black;\n";
codestr=codestr+"TEXT-DECORATION: underline\n";
codestr=codestr+"}\n";
codestr=codestr+"A:hover\n";
codestr=codestr+"{\n";
codestr=codestr+"    COLOR: black;\n";
codestr=codestr+"    TEXT-DECORATION: underline\n";
codestr=codestr+"}\n";
codestr=codestr+"-->\n";
codestr=codestr+"</style>\n";
codestr=codestr+"<SCRIPT LANGUAGE=javascript FOR=document EVENT=onkeyup>\n";
codestr=codestr+"<!--\n";
codestr=codestr+"document_onkeyup();\n";
codestr=codestr+"//-->\n";
codestr=codestr+"</SCRIPT>\n";
codestr=codestr+"<script language=javascript>\n";
codestr=codestr+"function document_onkeyup() {\n";
codestr=codestr+"if ((event.altKey==true && event.keyCode==83) || (event.ctrlKey==true && event.keyCode==13))\n";
codestr=codestr+"	{	\n";
codestr=codestr+"		if (check_form())\n";
codestr=codestr+"		document.form.submit();\n";
codestr=codestr+"	}\n";
codestr=codestr+"else if (event.altKey==true && event.keyCode==67)\n";
codestr=codestr+"	window.close();\n";
codestr=codestr+"}\n";
codestr=codestr+"\n";
codestr=codestr+"function check_form()\n";
codestr=codestr+"{\n";
codestr=codestr+"	if (form.info.value==\"\")\n";
codestr=codestr+"		{\n";
codestr=codestr+"			alert(\"不能发送空信息！\");\n";
codestr=codestr+"			form.info.focus();\n";
codestr=codestr+"			return(false);\n";
codestr=codestr+"		}\n";
codestr=codestr+"	if (form.info.value.length>100)\n";
codestr=codestr+"		{\n";
codestr=codestr+"			alert(\"发送信息太长，不能超过100个汉字！\");\n";
codestr=codestr+"			form.info.focus();\n";
codestr=codestr+"			return(false);\n";
codestr=codestr+"		}\n";
codestr=codestr+"	if (form.info.value.indexOf(\"$\")!=-1 || form.info.value.indexOf(\"|\")!=-1 )\n";
codestr=codestr+"		{\n";
codestr=codestr+"			alert(\"信息中不能含有$,|字符！\");\n";
codestr=codestr+"			form.info.focus();\n";
codestr=codestr+"			return(false);\n";
codestr=codestr+"		}\n";
codestr=codestr+"	form.send.disabled=true;\n";
codestr=codestr+"	window.moveTo(1100,700);\n";
codestr=codestr+"	return(true);\n";
codestr=codestr+"}\n";
codestr=codestr+"</script>\n";
codestr=codestr+"</head>\n";
codestr=codestr+"<body bgcolor=\"#ffffff\" scroll=no leftmargin=\"0\" topmargin=\"0\">\n";
codestr=codestr+"<form method=\"post\" name=\"form\" action=\"writesendinfo.asp\" onsubmit=\"return check_form()\">\n";
codestr=codestr+"	 <input id=\"backinfo\" name=\"backinfo\" type=\"hidden\" value=\"\">";
codestr=codestr+"<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"354\" bgcolor=\"#E7E7E7\">\n";
codestr=codestr+"  <tr>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"2\" height=\"1\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"77\" height=\"1\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"85\" height=\"1\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"154\" height=\"1\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"17\" height=\"1\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"17\" height=\"1\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"2\" height=\"1\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"1\" height=\"1\" border=\"0\"></td>\n";
codestr=codestr+"  </tr>\n";
codestr=codestr+"\n";
codestr=codestr+"  <tr>\n";
codestr=codestr+"   <td colspan=\"7\"><img name=\"porm_r1_c1\" src=\"../qqpic/info/porm_r1_c1.gif\" width=\"354\" height=\"2\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"1\" height=\"2\" border=\"0\"></td>\n";
codestr=codestr+"  </tr>\n";
codestr=codestr+"  <tr>\n";
codestr=codestr+"   <td rowspan=\"5\"><img name=\"porm_r2_c1\" src=\"../qqpic/info/porm_r2_c1.gif\" width=\"2\" height=\"240\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img name=\"porm_r2_c2\" src=\"../qqpic/info/title.gif\" width=\"77\" height=\"16\" border=\"0\"></td>\n";
codestr=codestr+"   <td colspan=\"2\" width=\"239\" height=\"16\" bgcolor=\"#BDBEBD\">\n";
codestr=codestr+"	<script src=\"dispgg.asp\"></script>\n";
codestr=codestr+"   </td>\n";
codestr=codestr+"   <td width=\"17\" height=\"16\" bgcolor=\"#BDBEBD\">\n";
codestr=codestr+"   </td>\n";
codestr=codestr+"   <td width=\"17\" height=\"16\" bgcolor=\"#BDBEBD\">\n";
codestr=codestr+"    <p align=\"center\"><img border=\"0\" src=\"../qqpic/Close.gif\" width=\"11\" height=\"11\"></p>\n";
codestr=codestr+"   </td>\n";
codestr=codestr+"   <td rowspan=\"5\"><img name=\"porm_r2_c7\" src=\"../qqpic/info/porm_r2_c7.gif\" width=\"2\" height=\"240\" border=\"0\"></td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"1\" height=\"16\" border=\"0\"></td>\n";
codestr=codestr+"  </tr>\n";
codestr=codestr+"  <tr>\n";
codestr=codestr+"   <td colspan=\"5\" width=\"350\" height=\"26\">\n";
codestr=codestr+"    <table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" height=\"100%\" bordercolorlight=\"#000000\" bordercolordark=\"#FFFFFF\">\n";
codestr=codestr+"      <tr>\n";
codestr=codestr+"        <td width=\"100%\" id=\"listinfo\" name=\"listinfo\">\n";
codestr=codestr+"          <p align=\"center\">\n";
codestr=codestr+"<script language=\"javascript\">\n";
codestr=codestr+"document.write(\"\"+opener.parent.username.value+\"在\"+opener.parent.sitename.value+\"发送信息\");\n";
codestr=codestr+"</script>\n";
codestr=codestr+"		   </p>\n";
codestr=codestr+"        </td>\n";
codestr=codestr+"      </tr>\n";
codestr=codestr+"    </table>\n";
codestr=codestr+"   </td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"1\" height=\"26\" border=\"0\"></td>\n";
codestr=codestr+"  </tr>\n";
codestr=codestr+"  <tr>\n";
codestr=codestr+"   <td colspan=\"2\" width=\"162\" height=\"40\">\n";
codestr=codestr+"    <table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" bordercolorlight=\"#000000\" height=\"100%\" bordercolordark=\"#FFFFFF\">\n";
codestr=codestr+"      <tr>\n";
codestr=codestr+"        <td width=\"100%\" valign=\"middle\">\n";
codestr=codestr+"          <p align=\"left\">请输入信息<br>\n";
codestr=codestr+"          请按Alt+S键发送信息</p>\n";
codestr=codestr+"        </td>\n";
codestr=codestr+"      </tr>\n";
codestr=codestr+"    </table>\n";
codestr=codestr+"   </td>\n";
codestr=codestr+"   <td colspan=\"3\" width=\"188\" height=\"40\" valign=\"middle\">\n";
codestr=codestr+"    <p align=\"center\"><img border=\"1\" src=\"../qqpic/info/dogbanner.gif\" width=\"186\" height=\"38\"></p>\n";
codestr=codestr+"   </td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"1\" height=\"40\" border=\"0\"></td>\n";
codestr=codestr+"  </tr>\n";
codestr=codestr+"  <tr>\n";
codestr=codestr+"   <td colspan=\"5\" width=\"350\" height=\"131\" valign=\"top\">\n";
codestr=codestr+"    <p align=\"left\"><textarea rows=\"5\" name=\"info\" cols=\"42\" style=\"height:131;width=350;font-family: \"宋体\"; font-size: 9pt;\"></textarea></p>\n";
codestr=codestr+"   </td>\n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"1\" height=\"131\" border=\"0\"></td>\n";
codestr=codestr+"  </tr>\n";
codestr=codestr+"  <tr>\n";
codestr=codestr+"   <td colspan=\"5\" width=\"350\" height=\"27\">&nbsp;<input type=\"submit\" value=\"发 送[S]\" name=\"send\" style=\"FONT-FAMILY: 宋体; FONT-SIZE: 9pt; HEIGHT: 20\">&nbsp;&nbsp;  \n";
codestr=codestr+"    &nbsp;&nbsp; <input type=\"button\" value=\"关 闭[C]\" name=\"close\" onclick=\"window.close();\" style=\"FONT-FAMILY: 宋体; FONT-SIZE: 9pt; HEIGHT: 20\"></td> \n";
codestr=codestr+"   <td><img src=\"../qqpic/info/spacer.gif\" width=\"1\" height=\"27\" border=\"0\"></td> \n";
codestr=codestr+"  </tr> \n";
codestr=codestr+"</table> \n";
codestr=codestr+"</form> \n";
codestr=codestr+"</body> \n";
codestr=codestr+"</html> \n";
codestr=codestr+"<script language=javascript> \n";
codestr=codestr+"form.backinfo.value=window.name+\"$\"+opener.parent.usersessionid.value+\"$\"+opener.parent.sitename.value+\"$\"+opener.parent.siteurl.value+\"$\"+opener.parent.username.value+\"$\";";
codestr=codestr+"</script> \n";
sendinfocode.value=codestr;
