<!--#INCLUDE FILE="inc_config.asp" -->
<html>
<head>
<title>广告位置</title>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<style type="text/css">
<!--
body      {  font-size: 10.4pt }
td        {  font-size: 10.4pt }
-->
</style>
</head>

<body bgcolor="#cccccc" text="<%=m_text2%>" style="margin:0"> 
<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
  <tr align="center" valign="bottom"> 
    <td><%=r_adcontent%></td>
    </tr>
    <tr bgcolor="<%=m_bg1%>"> 
      <td height="1"></td>
    </tr>
  </table>
</body>
</html>