<%
Const EPS_SUCCESS = &H0
Const EPS_CANNOT_OPEN_DRIVER = &H1
Const EPS_INVALID_DRVR_VERSION = &H2
Const EPS_INVALID_COMMAND = &H3
Const EPS_ACCESS_DENIED = &H4
Const EPS_ALREADY_ZERO = &H5
Const EPS_UNIT_NOT_FOUND = &H6
Const EPS_DEVICE_REMOVED = &H7
Const EPS_COMMUNICATIONS_ERROR = &H8
Const EPS_DIR_NOT_FOUND = &H9
Const EPS_FILE_NOT_FOUND = &HA
Const EPS_MEM_CORRUPT = &HB
Const EPS_INTERNAL_HW_ERROR = &HC
Const EPS_INVALID_RESP_SIZE = &HD
Const EPS_PIN_EXPIRED = &HE
Const EPS_ALREADY_EXISTS = &HF
Const EPS_NOT_ENOUGH_MEMORY = &H10
Const EPS_INVALID_PARAMETER = &H11
Const EPS_ALIGNMENT_ERROR = &H12
Const EPS_INPUT_TOO_LONG = &H13
Const EPS_INVALID_FILE_SELECTED = &H14
Const EPS_DEVICE_IN_USE = &H15
Const EPS_INVALID_CONTEXT = &H16
Const EPS_CANTDECREMENT = &H17
Const EPS_INVALID_STATUS = &HFF

' Flags used by EPS_OpenDevice()

Const EPS_OPEN_NEXT = &H0
Const EPS_OPEN_FIRST = &H1
Const EPS_OPEN_CURRENT = &H2

' EPS_FILEINFO.Type

Const EPS_FILETYPE_UNUSED = &H0
Const EPS_FILETYPE_DIR = &H1
Const EPS_FILETYPE_DATA = &H2
Const EPS_FILETYPE_COUNTER = &H3
Const EPS_FILETYPE_KEY = &H4
Const EPS_FILETYPE_UNKNOWN = &HFF

' EPS_FILEINFO access types

Const EPS_ACCESS_ALWAYS = &H0
Const EPS_ACCESS_PIN = &H1
Const EPS_ACCESS_MASTERKEY = &H2
Const EPS_ACCESS_NEVER = &H7

' EPS_CONTEXT.FileAccess definition

Const EPS_ACCESS_READ = &H1
Const EPS_ACCESS_WRITE = &H2
Const EPS_ACCESS_CRYPT = &H4

' LED state controls

Const EPS_LED_SYSPOWER = &H0
Const EPS_LED_ON = &H1
Const EPS_LED_OFF = &H2
%>